---
redisStandalone:
  image: quay.io/opstree/redis
  tag: v6.2.5
  imagePullPolicy: IfNotPresent
  # redisSecret:
  #   secretName: redis-secret
  #   secretKey: password
  serviceType: ClusterIP
  # name: ot-container-kit-redis
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

externalService:
  # name: ot-container-kit-external-service
  enabled: false
  # annotations:
  #   foo: bar
  serviceType: NodePort
  port: 6379

serviceMonitor:
  # name: ot-container-kit-prometheus-monitoring
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  namespace: monitoring

redisExporter:
  enabled: true
  image: quay.io/opstree/redis-exporter
  tag: "1.0"
  imagePullPolicy: IfNotPresent
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
  # env:
  # - name: REDIS_EXPORTER_INCL_SYSTEM_METRICS
  #   value: "true"
  # - name: UI_PROPERTIES_FILE_NAME
  #   valueFrom:
  #     configMapKeyRef:
  #       name: game-demo
  #       key: ui_properties_file_name
  # - name: SECRET_USERNAME
  #   valueFrom:
  #     secretKeyRef:
  #       name: mysecret
  #       key: username

# priorityClassName: "-"

# imagePullSecrets:
#  - name: regcred

nodeSelector: {}
  # memory: medium

storageSpec:
  volumeClaimTemplate:
    spec:
      # storageClassName: standard
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  #   selector: {}

securityContext: {}
  # runAsUser: 1000

affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: disktype
  #         operator: In
  #         values:
  #         - ssd
